describe("Load referee signals page and render referee signals", () => {
  beforeEach(() => {
    cy.intercept('GET', 'https://derby-api.herokuapp.com/api/v1/handsignals', { fixture: "handSignal.json" })
      .visit("http://localhost:3000")
  })
  it("Should be able to visit the page and render title", () => {
    cy.get("[data-testid=title]")
      .should("be.visible")
  })
  it('should be able to see and click the checkbox', () => {
    cy.get("[data-testid=signals-container]")
      .get("[data-testid=checkbox]")
      .check()
  })
  it('should be able to visit the page and see all the referee signals', () => {
    cy.get("[data-testid=signals-container]")
      .get("[data-testid=card-holder]")
      .get("[data-testid=link]")
      .get("[data-testid=card]")
      .get("[data-testid=image-div]")
      .get("[data-testid=image]")
      .should("have.attr", "src")
  })
  it('should be able to click the checkbox and see filtered signals', () => {
    cy.get("[data-testid=signals-container]")
      .get("[data-testid=card-holder]")
      .get("[data-testid=link]")
      .get("input[type=checkbox]").check({force: true})
      .get("[data-testid=card]")
      .get("[data-testid=image-div]")
      .get("[data-testid=image]")
      .should("have.attr", "src")
  })
  it('should be able to check the checkbox and see filtered signals then uncheck and see all referee signals', () => {
    cy.get("[data-testid=signals-container]")
      .get("[data-testid=card-holder]")
      .get("[data-testid=link]")
      .get("input[type=checkbox]").check({ force: true })
      .get("[data-testid=card]")
      .get("[data-testid=image-div]")
      .get("[data-testid=image]")
      .should("have.attr", "src")
      .get("input[type=checkbox]").uncheck({ force: false })
  })
})